// <auto-generated />
using System;
using DbConfig.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace DbConfig.Provider.SqlServer.Migrations;

[DbContext(typeof(DbConfigDbContext))]
partial class DbConfigDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("DbConfig.EntityFrameworkCore.ConfigAuditEntryEntity", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Scope")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)")
                .UseCollation("Latin1_General_100_BIN2");

            b.Property<string>("Environment")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)")
                .UseCollation("Latin1_General_100_BIN2");

            b.Property<string>("TenantId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)")
                .UseCollation("Latin1_General_100_BIN2");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("nvarchar(512)")
                .UseCollation("Latin1_General_100_BIN2");

            b.Property<string>("OldValue")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("NewValue")
                .HasColumnType("nvarchar(max)");

            b.Property<bool>("IsSecret")
                .HasColumnType("bit");

            b.Property<string>("Action")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("nvarchar(16)");

            b.Property<DateTimeOffset>("ModifiedUtc")
                .HasColumnType("datetimeoffset");

            b.Property<string>("ModifiedBy")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.HasKey("Id");

            b.HasIndex("Scope", "Environment", "TenantId", "Key", "ModifiedUtc")
                .HasDatabaseName("IX_DbConfig_Audit_Scope_Environment_TenantId_Key_ModifiedUtc");

            b.ToTable("DbConfig_AuditEntries");
        });

        modelBuilder.Entity("DbConfig.EntityFrameworkCore.ConfigEntryEntity", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Scope")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)")
                .UseCollation("Latin1_General_100_BIN2");

            b.Property<string>("Environment")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)")
                .UseCollation("Latin1_General_100_BIN2");

            b.Property<string>("TenantId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)")
                .UseCollation("Latin1_General_100_BIN2");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("nvarchar(512)")
                .UseCollation("Latin1_General_100_BIN2");

            b.Property<string>("Value")
                .HasColumnType("nvarchar(max)");

            b.Property<bool>("IsSecret")
                .HasDefaultValue(false)
                .HasColumnType("bit");

            b.Property<DateTimeOffset>("ModifiedUtc")
                .HasColumnType("datetimeoffset");

            b.Property<string>("ModifiedBy")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.HasKey("Id");

            b.HasIndex("Scope", "Environment", "TenantId", "ModifiedUtc")
                .HasDatabaseName("IX_DbConfig_Entries_Scope_Environment_TenantId_ModifiedUtc");

            b.HasIndex("Scope", "Environment", "TenantId", "Key")
                .IsUnique()
                .HasDatabaseName("UX_DbConfig_Entries_Scope_Environment_TenantId_Key");

            b.ToTable("DbConfig_Entries");
        });
#pragma warning restore 612, 618
    }
}
