services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: paymentsapi
      POSTGRES_USER: paymentsapi
      POSTGRES_PASSWORD: paymentsapi
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
