// <auto-generated />
using System;
using DbConfig.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DbConfig.Provider.PostgreSql.Migrations;

[DbContext(typeof(DbConfigDbContext))]
[Migration("20260516000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("DbConfig.EntityFrameworkCore.ConfigEntryEntity", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("AppName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("text");

            b.Property<string>("Environment")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("text");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("text");

            b.Property<string>("Value")
                .HasColumnType("text");

            b.Property<bool>("IsSecret")
                .HasDefaultValue(false)
                .HasColumnType("boolean");

            b.Property<DateTime>("ModifiedUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("ModifiedBy")
                .HasMaxLength(256)
                .HasColumnType("text");

            b.HasKey("Id");

            b.HasIndex("AppName", "Environment", "ModifiedUtc")
                .HasDatabaseName("IX_DbConfig_Entries_AppName_Environment_ModifiedUtc");

            b.HasIndex("AppName", "Environment", "Key")
                .IsUnique()
                .HasDatabaseName("UX_DbConfig_Entries_AppName_Environment_Key");

            b.ToTable("DbConfig_Entries");
        });
#pragma warning restore 612, 618
    }
}
